import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-scrap-metal-recycling-revenue-reconciliation",
  "engine": "recovery",
  "title": "Scrap Metal & Recycling Revenue Reconciliation",
  "shortTitle": "Scrap Metal and Recycling Revenue Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through scrap metal & recycling revenue reconciliation",
  "industry": "Recycling Revenue Assurance",
  "uiPort": 4612,
  "apiPort": 5612,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Scrap Metal & Recycling Revenue Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedRevenue",
    "expectedKey": "supportedRevenue",
    "actualLabel": "Recycler Settlement Revenue",
    "expectedLabel": "Index-Supported Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Scrap Metal & Recycling Revenue Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("recycler-contract-library","SMR01","Recycler contract library","Execute recycler contract library using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed recycler contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Recycler contract library Reference","text","SMR01-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("commodity-grade-registry","SMR02","Commodity grade registry","Execute commodity grade registry using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed commodity grade registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Commodity grade registry Reference","text","SMR02-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("container-pickup-tracking","SMR03","Container pickup tracking","Execute container pickup tracking using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed container pickup tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Container pickup tracking Reference","text","SMR03-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("scale-ticket-ingestion","SMR04","Scale ticket ingestion","Execute scale ticket ingestion using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed scale ticket ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Scale ticket ingestion Reference","text","SMR04-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("gross-tare-net-validation","SMR05","Gross tare net validation","Execute gross tare net validation using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed gross tare net validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Gross tare net validation Reference","text","SMR05-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("moisture-deduction-audit","SMR06","Moisture deduction audit","Execute moisture deduction audit using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed moisture deduction audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Moisture deduction audit Reference","text","SMR06-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("contamination-deduction-audit","SMR07","Contamination deduction audit","Execute contamination deduction audit using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed contamination deduction audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Contamination deduction audit Reference","text","SMR07-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("commodity-index-pricing","SMR08","Commodity index pricing","Execute commodity index pricing using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed commodity index pricing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Commodity index pricing Reference","text","SMR08-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("recovery-percentage-validation","SMR09","Recovery percentage validation","Execute recovery percentage validation using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed recovery percentage validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Recovery percentage validation Reference","text","SMR09-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("hauling-fee-audit","SMR10","Hauling fee audit","Execute hauling fee audit using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed hauling fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Hauling fee audit Reference","text","SMR10-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("floor-price-control","SMR11","Floor price control","Execute floor price control using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed floor price control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Floor price control Reference","text","SMR11-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("settlement-matching","SMR12","Settlement matching","Execute settlement matching using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed settlement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Settlement matching Reference","text","SMR12-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("missing-pickup-detection","SMR13","Missing pickup detection","Execute missing pickup detection using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed missing pickup detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Missing pickup detection Reference","text","SMR13-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("recycler-claim-workflow","SMR14","Recycler claim workflow","Execute recycler claim workflow using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed recycler claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Recycler claim workflow Reference","text","SMR14-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]}),
feature("plant-commodity-analytics","SMR15","Plant commodity analytics","Execute plant commodity analytics using recycler contracts, commodities, grades, containers, pickups, scale tickets, weights, moisture, contamination, indexes, hauling fees, settlements, and cash.","Produce a governed plant commodity analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recycler / Plant Commodity","text","Recycler / Plant Commodity · Standard Case"],["caseReference","Plant commodity analytics Reference","text","SMR15-2026-001"],["receivedRevenue","Recycler Settlement Revenue","currency",808500],["supportedRevenue","Index-Supported Revenue","currency",954030],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRevenue",subjects:["Recycler contract library case","Commodity grade registry case","Container pickup tracking case","Scale ticket ingestion case","Gross tare net validation case"]})
]);
